version: '3.8'

services:
  client-service:
    build:
      context: ./ClientService
      dockerfile: ClientService.Api/Dockerfile
    ports:
      - "5001:8080"
    environment:
      - ConnectionStrings__DefaultConnection=${DEFAULT_CONNECTION}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge